# Generated by Django 3.0.2 on 2020-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='caption',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
