# Generated by Django 3.0.2 on 2020-02-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
