# Generated by Django 3.0.2 on 2020-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
