# Generated by Django 3.0.2 on 2020-03-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currentuserview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUserView',
        ),
    ]
