# Generated by Django 3.0.2 on 2020-03-09 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_currentuserview'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
