# Generated by Django 3.0.3 on 2020-04-06 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200405_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='post',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
