# Generated by Django 3.0.2 on 2020-02-17 04:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200216_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='profile',
            field=models.CharField(default='null', max_length=40, verbose_name=api.models.Profile),
        ),
    ]
