# Generated by Django 3.0.4 on 2020-05-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200427_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='forumPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ForumPost'),
        ),
    ]
