# Generated by Django 3.0.3 on 2020-02-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200217_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
