# Generated by Django 3.0.2 on 2020-02-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200216_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
