# Generated by Django 3.0.3 on 2020-03-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200324_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friendID',
        ),
        migrations.AlterField(
            model_name='friends',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
