# Generated by Django 3.0.2 on 2020-02-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200216_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='profile',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
