# Generated by Django 3.0.3 on 2020-02-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dummy1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy1',
        ),
    ]
