# Generated by Django 3.0.4 on 2020-04-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200405_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='profile',
        ),
    ]
