# Generated by Django 3.0.2 on 2020-02-17 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200216_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='user',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Profile'),
            preserve_default=False,
        ),
    ]
