# Generated by Django 3.0.3 on 2020-02-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200212_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usertest',
            name='userName',
        ),
    ]
