# Generated by Django 3.0.2 on 2020-02-17 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20200216_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='profile_ptr',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedpost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='caption',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='post',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
