# Generated by Django 3.0.4 on 2020-03-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200325_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friendID',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friedID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('userID', 'friedID')},
        ),
        migrations.AlterIndexTogether(
            name='friendship',
            index_together={('userID', 'friedID')},
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='userOne',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='userTwo',
        ),
    ]
