# Generated by Django 3.0.2 on 2020-03-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_groupworkout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupworkout',
            name='user',
        ),
    ]
