# Generated by Django 3.0.4 on 2020-04-12 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20200411_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='profile',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
