# Generated by Django 3.0.3 on 2020-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200212_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('caption', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
