# Generated by Django 3.0.2 on 2020-02-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200216_2122'),
        ('api', '0003_auto_20200216_2100'),
    ]

    operations = [
    ]
