# Generated by Django 3.0.4 on 2020-03-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200325_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='user',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
            preserve_default=False,
        ),
    ]
