<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-03-23 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_groupworkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
=======
# Generated by Django 3.0.2 on 2020-03-23 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_remove_groupworkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
>>>>>>> d8e701ff5fa2b19fdd435c0a33ccf9852ff56f2d
