# Generated by Django 3.0.4 on 2020-04-12 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200411_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
