# Generated by Django 3.0.3 on 2020-04-13 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_forumpost_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.AddField(
            model_name='like',
            name='feedpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.FeedPost'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
