# Generated by Django 3.0.3 on 2020-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200323_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountType',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=10),
        ),
    ]
