# Generated by Django 3.0.4 on 2020-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_forumpost_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
