# Generated by Django 3.0.3 on 2020-04-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200412_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='userID',
            field=models.IntegerField(null=True),
        ),
    ]
