# Generated by Django 3.0.3 on 2020-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200324_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountType',
            field=models.CharField(default='private', max_length=10),
        ),
    ]
