# Generated by Django 3.0.4 on 2020-04-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200412_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
