# Generated by Django 3.0.2 on 2020-04-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
