# Generated by Django 3.0.3 on 2020-04-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200412_1852'),
        ('api', '0013_comment_date'),
    ]

    operations = [
    ]
